### ISSUE TITLE
Please don't use pristine git head...

### ISSUE THREAD

**Issue by steve8x8** [lekum/geotoad-docker#1]
... as it lacks proper version information (at least as it is now).
"CURRENT" is just a placeholder and should not be used anywhere in "production" scenarios.

This may lead to confusion (and indeed did, see https://github.com/steve8x8/geotoad/issues/326):
While the VERSION file still shows the previous release, subsequent commits may have introduced new features or bugs.

Please see https://github.com/steve8x8/geotoad/blob/master/tools/build/Makefile for what gets done between cloning git, and creating a release tarball. 

Ideally, the %VERSION% string (in three files) would be replaced something like

```
`cat VERSION`+`date +%Y%m%d`-`git log | head -n1 | cut -c8-14`
```

Thanks!

**Comment by lekum** [comment]
I'll take a look on that as soon as I can. Thanks!
